* rollenKurator -- Run multiple commands simultaneously, with seperately paned output
  This was origally intended as a "plugin" for Ansible Powerplay, but can stand on its
  own. This is my first Haskell as my first Haskell project, both
  to aid in my learning Haskell and also to do fast handling of the playbook output.

  I love Ruby, but for some things I need really fast performance, and if you are
  running a number of Ansible playbooks in parallel via Powerplay, a lot of output
  will be generated that needs to be handled quickly and responsibly.

  Also, this is meant to be an alternative to using Tmux for those not willing
  to tool up in that fashion.

  rollenKurator creates its own 'panes' and tightly interacts with Powerplay, thoough
  it can stand alone as well. 
** Features
   Here we list some of the many (upcoming) features of rollenKurator.

*** Dynamic Panes
    Panes are created dynamically as concurrent processed are launched. Panes can
    have their geometry dymically changed.

*** Filtering
    Means to filter the output, so that non-revelant content is collapsed. With a keystroke
    the collapsed text can be expanded.

*** Colored Output maintained
    The commands are run as pseudo terminals, so that the colored output can be used.

** IN PROGRESS
   Your imput is welcome, as always.
   
** Linux supported initially
   I am not really interested in supporting Macs nor Windows. However, I will accept
   pull requests for those platforms.

** Release Notes
   | Version                  | Details       |
   |--------------------------+---------------|
   | Nothing to see here yet. | Move it along |
   |                          |               |

** Scratchpad
** Junkyard
